// Pixel-art sprites for the Reino, rendered from string maps (no image assets).
// Each character in a row maps to a colour in PAL; "." (or any unknown char) is
// transparent. Verified visually in the design mockup before integration.

const PAL: Record<string, string | undefined> = {
  ".": undefined,
  o: "#0a1024",
  S: "#f2cda6",
  s: "#d39e75",
  E: "#1b2140",
  W: "#ffffff",
  K: "#ffd24a",
  y: "#fff0b0",
  k: "#c98a10",
  P: "#8b5cf6",
  p: "#6d28d9",
  q: "#c4b5fd",
  R: "#ef4444",
  r: "#b91c1c",
  M: "#c3d0ef",
  m: "#8595c4",
  i: "#51608f",
  B: "#38bdf8",
  b: "#1d76ad",
  G: "#34d399",
  g: "#1f9e6b",
  T: "#2dd4bf",
  t: "#178b7e",
  C: "#22d3ee",
  A: "#fbbf24",
  a: "#b9810f",
  N: "#8a5a2b",
  n: "#5e3c1c",
  X: "#f49ac1",
  x: "#cf6f9f",
  V: "#7c3aed",
  L: "#93a3c9",
  l: "#5d6b96",
  D: "#38456f",
  H: "#22c55e",
};

export const SPRITES = {
  king: [
    "...o......o...",
    "..oKo....oKo..",
    "..oKyo..oyKo..",
    ".oKKKKKKKKKKo.",
    ".oKyKyKyKyKyo.",
    ".okBkkBkkBko..",
    "..oSSSSSSSSo..",
    "..oSEWSSWESo..",
    "..oSSSSSSSSo..",
    "..osSWWWWSso..",
    ".oPPPPPPPPPPo.",
    "oRqPPPPPPPPqRo",
    "oRPPPPPPPPPPRo",
    "oRPPPqqqPPPPRo",
    "oRoPPPPPPPPoRo",
    ".ooPPPPPPPPoo.",
    "..oNNo..oNNo..",
    "..onno..onno..",
  ],
  kingSeat: [
    "...o......o...",
    "..oKo....oKo..",
    "..oKyo..oyKo..",
    ".oKKKKKKKKKKo.",
    ".oKyKyKyKyKyo.",
    ".okBkkBkkBko..",
    "..oSSSSSSSSo..",
    "..oSEWSSWESo..",
    "..oSSSSSSSSo..",
    "..osSWWWWSso..",
    ".oPPPPPPPPPPo.",
    "oRqPPPPPPPPqRo",
    "oRPPPPPPPPPPRo",
    "oRPPqqqqqPPPRo",
    ".oPPPPPPPPPPo.",
    ".oNNNoooNNNo..",
    ".onnno.onnno..",
  ],
  guardian: [
    "....oooo....",
    "...oMMMMo...",
    "..oMMMMMMo..",
    "..oMiEEiMo..",
    "..oMMMMMMo..",
    "..oSSSSSSo..",
    "..oSEssESo..",
    "..oSSSSSSo..",
    ".BoMMMMMMoi.",
    ".BBMMMMMMii.",
    ".BBoMMMMoii.",
    ".BBiMmmMiii.",
    ".oBoMMMMoio.",
    "...immmmi...",
    "...oii.iio..",
    "...onn.nno..",
  ],
  brain: [
    "..oXXXXXXo..",
    ".oXxXXxXXXo.",
    ".oXXXXxXXXo.",
    ".oXxXXXxXXo.",
    "..oXXXXXXo..",
    "..oSSSSSSo..",
    ".oWEWoWEWo..",
    "..oSSSSSSo..",
    "..osSEESso..",
    ".oGGGGGGGGo.",
    "oGGgGGGGgGGo",
    "oGGGGGGGGGGo",
    ".oGGGGGGGGo.",
    "..oGGGGGGo..",
    "..ogg..ggo..",
    "..onn..nno..",
  ],
  scout: [
    "...oooooo.....",
    "..oNNNNNNNo...",
    ".oNNNNNNNNNo..",
    "..ooSSSSoo....",
    "..oSSSSSSo....",
    "..oSEsSoMMMC..",
    "..oSSSSSoSo...",
    "..osSSSso.....",
    "..oCCCCCCo....",
    ".oCCCCCCCCo...",
    ".oCtCCCCtCo...",
    ".oCCCCCCCCo...",
    "..oCCCCCCo....",
    "..oCC.CCo.....",
    "..oNN.NNo.....",
    "..onn.nno.....",
  ],
  guide: [
    "....ooo......",
    "...oVVVo.....",
    "...oVVVo.....",
    "..oVVVVVo....",
    ".oVVVVVVVo...",
    "oVVVVVVVVVo..",
    "oVVVVVVVVVo..",
    ".oSSSSSSSo...",
    ".oSEsSsESo...",
    ".oSSWWWSSo...",
    ".oWWWWWWWo...",
    "oTWWWWWWWTo..",
    "oTWWWWWWWTo..",
    ".TWWWWWWWT...",
    ".ToWWWWWoT...",
    ".To.WWW.oT...",
    ".oToWWWoTo...",
    ".oTTTTTTTo...",
    "..onnnnno...",
  ],
  worker: [
    "..........MMM.",
    "..........MMM.",
    "...........N..",
    "...........N..",
    "..oAAAAAAo.N..",
    ".oAAAAAAAASN..",
    ".oaAAAAAAao...",
    "..oSSSSSSo....",
    "..oSEssESo....",
    "..oSSSSSSo....",
    ".SOoOOOOOo....",
    ".OOoOWWOOo....",
    "..oOOOOOOo....",
    "..oOOOOOOo....",
    "..oOO.OOo.....",
    "..oii.iio.....",
    "..onn.nno.....",
  ],
  castle: [
    "H...........",
    "Ho.o.o.o.o..",
    "HLLLLLLLLLL.",
    "oLLLBLLBLLLo",
    ".oLLLLLLLLo.",
    ".oLo.oo.oLo.",
    ".oLLLLLLLLo.",
    ".oLLLBLLLLo.",
    ".oLLLLLLLLo.",
    "oLLLLLLLLLLo",
    "oDDDDDDDDDDo",
    "oDDoDDDDoDDo",
  ],
  // Castillo en obras: andamios alrededor de muros a medio levantar.
  castleBuilding: [
    "N........N..",
    "NNNNNNNNNNN.",
    "N.oLLLLo.N..",
    "N.LLLLLL.N..",
    "NNNNNNNNNNN.",
    "N.LLLLLL.N..",
    "N.LLllLL.N..",
    "NoLLLLLLoN..",
    "oLLLLLLLLo..",
    "oDDDDDDDDo..",
    "oDDoDDDDoDo.",
  ],

  // ── Props de ambientación por zona ──────────────────────────────────────
  // 🔨 Obras
  bricks: [
    "oooooooooo",
    "orrorrroro",
    "orrorrroro",
    "oooooooooo",
    "rrorrrorro",
    "rrorrrorro",
    "oooooooooo",
  ],
  barrel: [
    "..oNNNNo..",
    ".oNnnnnNo.",
    "nNNNNNNNNn",
    ".oNnnnnNo.",
    "nNNNNNNNNn",
    ".oNnnnnNo.",
    "..oNNNNo..",
  ],
  // 🧪 Laboratorio
  flask: [
    "...oMMo...",
    "...oMMo...",
    "...oMMo...",
    "..oMMMMo..",
    ".oMGGGGMo.",
    ".oGGGGGGo.",
    ".oGGGGGGo.",
    "..oMMMMo..",
  ],
  potion: [
    "...oo...",
    "..oMMo..",
    "..oCCo..",
    ".oCCCCo.",
    ".oCXXCo.",
    ".oCCCCo.",
    "..oCCo..",
    "...oo...",
  ],
  // 🛡️ Guardia
  torch: [
    "...A...",
    "..AaA..",
    "..AAA..",
    "..yAy..",
    "...N...",
    "...n...",
    "...N...",
    "...n...",
  ],
  wallshield: [
    ".oMMMMo.",
    "oMMBBMMo",
    "oMBBBBMo",
    "oMMBBMMo",
    ".oMMMMo.",
    "..oMMo..",
    "...oo...",
  ],
  // 📜 Biblioteca
  bookshelf: [
    "oNNNNNNNNo",
    "oRGBAyRGBo",
    "oNNNNNNNNo",
    "oGAyRGBARo",
    "oNNNNNNNNo",
    "oBRGAyBGRo",
    "oNNNNNNNNo",
  ],
  candle: [
    "...A...",
    "...y...",
    "..oWo..",
    "..oWo..",
    "..oWo..",
    ".oWWWo.",
    ".oWWWo.",
  ],
  // 🔭 Mirador
  telescope: [
    ".....oMM",
    "....oMMo",
    "...oMMo.",
    "..oMMo..",
    "..oCo...",
    ".oNo....",
    ".N.N....",
    "oN..No..",
  ],
  star: [
    "....K....",
    "....K....",
    "..KKKKK..",
    "KKKKKKKKK",
    ".KKKKKKK.",
    "..KK.KK..",
    ".K....K..",
  ],
  moon: [
    "..yyyy..",
    ".yy..y..",
    ".y......",
    ".y......",
    ".y......",
    ".yy..y..",
    "..yyyy..",
  ],
} as const;

export type SpriteName = keyof typeof SPRITES;

// The "O" worker-vest colour isn't in the shared palette (it reuses orange);
// add it here so the worker renders correctly.
const EXTRA: Record<string, string> = { O: "#c2703a" };

/** Render a sprite as a crisp pixel grid at the given pixel scale. */
export function Pixel({ name, scale }: { name: SpriteName; scale: number }) {
  const rows = SPRITES[name];
  const width = Math.max(...rows.map((r) => r.length));
  return (
    <div
      className="pixel"
      style={{
        gridTemplateColumns: `repeat(${width}, ${scale}px)`,
        gridTemplateRows: `repeat(${rows.length}, ${scale}px)`,
      }}
    >
      {rows.flatMap((row, y) =>
        Array.from({ length: width }, (_, x) => {
          const ch = row[x] ?? ".";
          const color = PAL[ch] ?? EXTRA[ch];
          return (
            <div key={`${y}-${x}`} style={color ? { background: color } : undefined} />
          );
        })
      )}
    </div>
  );
}
